### PR TITLE
DelayedJob, Sidekiq, Resque, ActiveJob governor implementations

### PR DESCRIPTION
**Pull request by naiyt**

### CODE REVIEW

**Comment by naiyt** [comment]
@broschb thoughts on this?

**Comment by naiyt** [comment]
Also added `ActiveJob` support. To use it you still have to specify one of the supported `queue_adapters` and then include the `HerokuJobGovernator::Hooks::ActiveJob` mixin to your `ActiveJob` class.

**Comment by naiyt** [comment]
Added `sidekiq` support. Currently used in conjunction with `ActiveJob`, because `sidekiq` hooks are weird (and almost all of our `sidekiq` tools are using `ActiveJob` anyway).

**Comment by naiyt** [comment]
Resque support added as well

**Review by broschb — APPROVED** [review]

**Pull request merged**
